// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';

export function Fetch(arg1:string):Promise<protocol.PengoResponse>;

export function Greet(arg1:string):Promise<string>;
